const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_APP_PASSWORD,
  },
});

// Email sent to admin when a visitor submits the contact form
async function sendContactNotification({
  name,
  email,
  phone,
  subject,
  message,
}) {
  try {
    const info = await transporter.sendMail({
      from: `"EduNextG Website" <${process.env.EMAIL_USER}>`,
      to: process.env.ADMIN_EMAIL,
      replyTo: email,
      subject: `New Contact Message: ${subject}`,

      text: `
You have received a new message from the EduNextG website.

Name: ${name}
Email: ${email}
Phone: ${phone || "Not provided"}
Subject: ${subject}

Message:
${message}
      `.trim(),

      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #14283d;">
          <h2 style="color: #06294f;">New Contact Message</h2>

          <p>You have received a new message from the EduNextG website.</p>

          <hr />

          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Phone:</strong> ${phone || "Not provided"}</p>
          <p><strong>Subject:</strong> ${subject}</p>

          <h3 style="color: #06294f;">Message</h3>

          <div style="
            padding: 15px;
            background: #f5f6f7;
            border-left: 4px solid #a6c93a;
            border-radius: 4px;
          ">
            ${message}
          </div>

          <hr />

          <p style="font-size: 13px; color: #667586;">
            This notification was automatically generated by the EduNextG website.
          </p>
        </div>
      `,
    });

    console.log("Email notification sent:", info.messageId);

    return info;
  } catch (error) {
    console.error("Email notification failed:", error);
    throw error;
  }
}


// Reply from admin dashboard to visitor
async function sendContactReply({
  name,
  email,
  subject,
  message,
}) {
  try {
    console.log(`Sending reply to ${email}...`);

    const info = await transporter.sendMail({
      from: `"EduNextG India LLP" <${process.env.EMAIL_USER}>`,
      to: email,
      replyTo: process.env.EMAIL_USER,

      // Email subject
      subject: `Re: ${subject}`,

      // Plain-text fallback
      text: `
EduNextG India LLP
Website Support Team

Subject: Re: ${subject}

Dear ${name},

Thank you for contacting EduNextG India LLP.

${message}

If you have any further questions, please feel free to contact us.

Regards,
EduNextG India LLP
Website Support Team

----------------------------------------
This email was sent in response to your message submitted through the EduNextG website.
      `.trim(),

      // Professional HTML email
      html: `
        <div style="
          margin: 0;
          padding: 40px 20px;
          background: #f4f7fb;
          font-family: Arial, Helvetica, sans-serif;
          color: #26364a;
        ">

          <div style="
            max-width: 650px;
            margin: 0 auto;
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 10px;
            overflow: hidden;
          ">

            <!-- HEADER -->
            <div style="
              background: #06294f;
              padding: 26px 32px;
            ">

              <h1 style="
                margin: 0;
                color: #ffffff;
                font-size: 22px;
                font-weight: 600;
              ">
                EduNextG India LLP
              </h1>

              <p style="
                margin: 6px 0 0;
                color: #dbeafe;
                font-size: 13px;
              ">
                Website Support Team
              </p>

            </div>


            <!-- EMAIL INFORMATION -->
            <div style="
              padding: 20px 32px;
              background: #f8fafc;
              border-bottom: 1px solid #e5e7eb;
            ">

              <table style="
                width: 100%;
                border-collapse: collapse;
                font-size: 14px;
              ">

                <tr>
                  <td style="
                    width: 80px;
                    padding: 5px 0;
                    color: #64748b;
                    font-weight: 600;
                  ">
                    To
                  </td>

                  <td style="
                    padding: 5px 0;
                    color: #26364a;
                  ">
                    ${name}
                    &lt;${email}&gt;
                  </td>
                </tr>

                <tr>
                  <td style="
                    padding: 5px 0;
                    color: #64748b;
                    font-weight: 600;
                  ">
                    Subject
                  </td>

                  <td style="
                    padding: 5px 0;
                    color: #06294f;
                    font-weight: 600;
                  ">
                    Re: ${subject}
                  </td>
                </tr>

              </table>

            </div>


            <!-- CONTENT -->
            <div style="
              padding: 32px;
            ">

              <p style="
                margin: 0 0 18px;
                font-size: 15px;
                line-height: 1.7;
              ">
                Dear <strong>${name}</strong>,
              </p>


              <p style="
                margin: 0 0 20px;
                font-size: 15px;
                line-height: 1.7;
              ">
                Thank you for contacting
                <strong>EduNextG India LLP</strong>.
              </p>


              <!-- MESSAGE -->
              <div style="
                margin: 24px 0;
                padding: 20px;
                background: #f8fafc;
                border: 1px solid #e2e8f0;
                border-left: 4px solid #06294f;
                border-radius: 6px;
              ">

                <div style="
                  font-size: 15px;
                  line-height: 1.8;
                  color: #334155;
                  white-space: pre-line;
                ">
                  ${message}
                </div>

              </div>


              <p style="
                margin: 20px 0;
                font-size: 14px;
                line-height: 1.7;
                color: #475569;
              ">
                If you have any further questions, please feel free
                to contact us again.
              </p>


              <!-- SIGNATURE -->
              <div style="
                margin-top: 30px;
                padding-top: 20px;
                border-top: 1px solid #e5e7eb;
              ">

                <p style="
                  margin: 0;
                  font-size: 14px;
                  line-height: 1.7;
                ">
                  Regards,<br />

                  <strong style="color: #06294f;">
                    EduNextG India LLP
                  </strong><br />

                  <span style="color: #64748b;">
                    Website Support Team
                  </span>
                </p>

              </div>

            </div>


            <!-- FOOTER -->
            <div style="
              padding: 18px 32px;
              background: #f8fafc;
              border-top: 1px solid #e5e7eb;
              text-align: center;
            ">

              <p style="
                margin: 0;
                color: #94a3b8;
                font-size: 12px;
                line-height: 1.6;
              ">
                This email was sent in response to your message
                submitted through the EduNextG website.
              </p>

            </div>

          </div>

        </div>
      `,
    });

    console.log(
      "Reply email sent successfully:",
      info.messageId
    );

    return info;

  } catch (error) {
    console.error("Reply email failed:", error);
    throw error;
  }
}

module.exports = {
  sendContactNotification,
  sendContactReply,
};